// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"database/sql"
)

type Message struct {
	ID         int64        `db:"id" json:"id"`
	FromID     int64        `db:"from_id" json:"from_id"`
	FromAuthid string       `db:"from_authid" json:"from_authid"`
	FromName   string       `db:"from_name" json:"from_name"`
	Message    string       `db:"message" json:"message"`
	CreatedAt  sql.NullTime `db:"created_at" json:"created_at"`
}

type User struct {
	ID     int64  `db:"id" json:"id"`
	Name   string `db:"name" json:"name"`
	Authid string `db:"authid" json:"authid"`
	Email  string `db:"email" json:"email"`
}
